#!/bin/bash
x=({0..230})
v=${x[$RANDOM % ${#x[@]}]}
c=$(tput setaf $v)
n='\033[0m' # No Color

# System Information
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(grep -c cpu[0-9] /proc/stat)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
LOADCPU=$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')
IPVPS=$(curl -s ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
DOMAIN=$(cat /etc/xray/domain)
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(date +'%H:%M:%S')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)

# Service Status
SSH_SERVICE=$(systemctl is-active ssh)
DROPBEAR_SERVICE=$(systemctl is-active dropbear)
HAPROXY_SERVICE=$(systemctl is-active haproxy)
XRAY_SERVICE=$(systemctl is-active xray)
NGINX_SERVICE=$(systemctl is-active nginx)

# Function to display menu
menu() {
 echo -e "$c System Information:"
 echo -e "$c Model:$n $MODEL"
 echo -e "$c CPU Cores:$n $CORE"
 echo -e "$c RAM:$n $USAGERAM/$RAM MB"
 echo -e "$c CPU Load:$n $LOADCPU"
 echo -e "$c IP Address:$n $IPVPS"
 echo -e "$c ISP:$n $ISP"
 echo -e "$c City:$n $CITY"
 echo -e "$c Domain:$n $DOMAIN"
 echo -e "$c Date:$n $DATEVPS"
 echo -e "$c Timezone:$n $TIMEZONE"
 echo -e "$c Server Online:$n $SERONLINE"
 echo -e ""
 echo -e "$c Service Status:"
 echo -e "$c SSH:$n $SSH_SERVICE"
 echo -e "$c Dropbear:$n $DROPBEAR_SERVICE"
 echo -e "$c HAProxy:$n $HAPROXY_SERVICE"
 echo -e "$c Xray:$n $XRAY_SERVICE"
 echo -e "$c Nginx:$n $NGINX_SERVICE"
 echo -e ""
 echo -e "$c Menu:$n"
 echo -e "$c 1$n SSH Menu"
 echo -e "$c 2$n VMESS Menu"
 echo -e "$c 3$n VLESS Menu"
 echo -e "$c 4$n Trojan Menu"
 echo -e "$c 5$n SHDWSK Menu"
 echo -e ""
}

# Main Menu
clear
menu
echo
read -p "Select menu: " opt
echo -e ""
case $opt in
 1)
  clear
  m-sshws
  ;;
 2)
  clear
  m-vmess
  ;;
 3)
  clear
  m-vless
  ;;
 4)
  clear
  m-trojan
  ;;
 5)
  clear
  m-ssws
  ;;
 *)
  clear
  menu
  ;;
esac
